rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<str:category_name_slug>/', views.show_category, name='category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<str:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout')
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from rango import views
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('rango/', include('rango.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
'''
!/usr/bin/python3.6
-*- coding: utf-8 -*-
File: models.py
Project: Tango with Django 2.0
File Created: Thursday, 3rd May 2018 12:41:48 pm
Author: Dennis, Wangyi (denniswangyi@gmail.com)
-----
Last Modified: Saturday, 12th May 2018 6:33:17 pm
Modified By: Dennis, Wangyi (denniswangyi@gmail.com>)
-----
Copyright 2018 - 2018 Dennis, Wangyi
'''
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.
class Category(models.Model):
    """目录主体数据模型"""
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Page(models.Model):
    '''页面链接主体数据模型'''
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
        return self.user.username

rango/forms.py
'''
!/usr/bin/python3.6
-*- coding: utf-8 -*-
File: forms.py
Project: Tango with Django 2.0
File Created: Saturday, 12th May 2018 6:14:26 pm
Author: Dennis, Wangyi (denniswangyi@gmail.com)
-----
Last Modified: Saturday, 12th May 2018 6:33:54 pm
Modified By: Dennis, Wangyi (denniswangyi@gmail.com>)
-----
Copyright 2018 - 2018 Dennis, Wangyi
'''

from django import forms
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name. ")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    class Meta:
        model = Page
        exclude = ('category', )

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
# !/usr/bin/python3.6
# -*- coding: utf-8 -*-
'''
File: views.py
Project: Tango with Django 2.0
File Created: Thursday, 3rd May 2018 12:41:48 pm
Author: Dennis, Wangyi (denniswangyi@gmail.com)
-----
Last Modified: Saturday, 12th May 2018 6:30:59 pm
Modified By: Dennis, Wangyi (denniswangyi@gmail.com>)
-----
Copyright 2018 - 2018 Dennis, Wangyi
'''
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler_serverside(request):
    vistis = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        vistis = vistis + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = vistis


def visitor_cookie_handler(request, response):
    visits = int(request.COOKIES.get('visits', '1'))

    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        response.set_cookie('last_visit', str(datetime.now()))
    else:
        response.set_cookie('last_visit', last_visit_cookie)
    response.set_cookie('visits', visits)

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    visitor_cookie_handler_serverside(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context=context_dict)
    return response


def about(request):
    # print(request.method)
    # print(request.user)
    context_dict = {'developer_name': 'Dennis'}

    visitor_cookie_handler_serverside(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    # 用来返回给模版文件注册是否成功的标识变量。
    # 初始设置为 False， 注册成功后设置为 True
    registed = False

    # 如果请求的类型是 POST， 那么我们将对提交的注册信息进行处理
    if request.method == 'POST':
        # 试图从原始提交的表格信息中提取有用的信息
        # 需要注意的是我们同时需要 UserForm 和 UserProfileForm的信息
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # 假如两个 Form的数据都通过校验...
        if user_form.is_valid() and profile_form.is_valid():
            # 将用户注册 Form 中的信息直接存入数据库
            user = user_form.save()

            # 使用 set_password方法，来对用户的密码进行哈希算法的加密
            # 加密完成后，应该更新用户的密码数据，以在数据库中保存
            user.set_password(user.password)
            user.save()

            # 现在开始处理用户档案数据的Form信息，因为我们还需要补充输入相关的属性数据
            # 所以我们在这里设置 commit=False ，来延迟数据被直接存入数据库
            # 当我们完成所有的设置工作后，再真正提交数据库保存，这样能保证数据的完整性，避免异常的BUG
            profile = profile_form.save(commit=False)
            profile.user = user

            # 在这里我们判断用户是否上传了头像图片
            # 如果用户上传了，那么我们需要从提交Form的数据中取出文件，并更新到我们的用户档案model中去
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # 现在我们对用户档案的模型进行保存，即存入了数据库
            profile.save()

            # 更新标识变量，以告诉模板我们已经注册成功了
            registed = True
        else:
            # 如果 Form 数据校验不通过——存在某些错误
            # 在 Terminal 中将错误打印出来
            print(user_form.errors, profile_form.errors)
    else:
        # 如果请求类型不是 POST，那么我们将用使用两个 ModelForm 的实例来进行模板渲染
        # 并且这两个实例的数据为空
        user_form = UserForm()
        profile_form = UserProfileForm()

    # 返回模板渲染，并传入上下文参数
    return render(
        request,
        'rango/register.html',
        {
            'user_form': user_form,
            'profile_form': profile_form,
            'registed': registed
        }
    )


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            error_msg = 'Your Rango account is disabled.'
            return render(request, 'rango/login.html', {'error_msg': error_msg})
        error_msg = "Invalid login detail supplied. "
        return render(request, 'rango/login.html', {'error_msg': error_msg})
    else:
        return render(request, 'rango/login.html', {})


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    About
{% endblock %}

{% block body_block%}
    {% if visits %}
        <p>visits is: {{visits}}</p>
    {% endif %}
    <div>
        This tutorial has been put together by
        <br />
        <strong>{{ developer_name }}</strong>
        <br />
    </div>
    <div>
        <img src="{{MEDIA_URL}}cat.jpeg" alt="Picture of cat" />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    Add Category
{% endblock %}

{% block body_block%}
    <h1>Add a Category</h1> 
    <div>
        <form id="category_form" method="POST" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.error }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Category" />
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    Add Page
{% endblock %}

{% block body_block%}
    {% if category %}
    <h1>Add a page in {{category.name}}</h1>
    <div>
        <form id="page_form" method="POST" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.error }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
        </form>
    </div>
    {% else %}
    <h1>A category by this name is not exist</h1>
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles%}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>Rango - 
            {%block title_block%}
                How to Tango with Django!
            {%endblock%}
        </title>
        <!--Css-->
        <link rel="stylesheet" href="{%static "css/base.css" %}" />
        <!--JS-->
        <script src="{%static "js/jquery.js" %}"></script>
    </head>
    <body>
        <div>
            {%block body_block%}
                This is body_block's default content.
            {%endblock%}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Sign In</a></li>
                {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list  category %}
            {% endblock %}
        </div>
    </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    {{category.name}}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{{ page.url }}">{{page.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category</strong>
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add a page</a>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            <li>
            {% if c == act_cat %}
                <strong><a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a></strong>
            {% else %}
                <a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a>
            {% endif %}
            </li>
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present. </strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    Index
{% endblock %}

{% block body_block%}
    <h1>Rango says...</h1>
    {% if user.is_authenticated %}
        hello {{ user.username }}
    {% else %}
        hey there partner!
    {% endif %}
    <div>
        <h2>Most Liked Categories</h2>
        {% if categories %}
        <ul>
            {% for category in categories %}
                <li>
                    <a href="{% url 'rango:category' category.slug %}"> {{ category.name }} </a> 
                    {{ category.likes }} likes
                </li>
            {% endfor%}
        </ul>
        {% else %}
            <strong>There are no categories present</strong>
        {% endif %}
    </div>
    <div>
        <h2>Most viewed Pages</h2>
            {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{{ page.url }}"> {{ page.title }} </a> 
                        {{ page.views }} views
                    </li>
                {% endfor%}
            </ul>
            {% else %}
                <strong>There are no pages present</strong>
            {% endif %}
    </div>
    <div>
        <br />
        <img src="{%static "images/rango.jpeg" %}" alt="Picture of Rango" />
    </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form name='login_form' method="POST" action="{% url 'rango:login' %}">
        {% csrf_token %}
        {% if error_msg %}
        <h2>{{ error_msg }}</h2>
        {% endif %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" name="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    Register
{% endblock %}

{% block body_block %}
    {% if registed %}
        Rango says: <strong>thanks for your registering! </strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        <form id='user_form' method="POST" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name='submit' value="Register" />
        </form>
    {% endif %}

{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block%}
    Restricted
{% endblock %}

{% block body_block%}
    <h1>Since you're login, you can see this text!</h1>
{% endblock %}